import type { Metadata } from "next";
import "./globals.css";
import { ray } from "@/next-persian-fonts/ray";
import { Toaster } from "react-hot-toast";
import { DailyBookProvider } from "@/contexts/DailyBookContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ray.className}>
        <Toaster
          gutter={12}
          position="top-center"
          reverseOrder={false}
          containerStyle={{
            direction: "rtl",
          }}
        />
        <DailyBookProvider> {children}</DailyBookProvider>
      </body>
    </html>
  );
}
